Perfitt-11-supreme/11-supreme

src/components/choose-shose/image-search/ImageSearch.tsx
src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
src/components/choose-shose/image-search/camera-window/cameracomponent/CameraComponent.tsx
src/components/choose-shose/image-search/camera-window/cameracomponent/cameracomponent.css.ts
src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
src/components/choose-shose/image-search/imagefooter/ImageFooter.tsx
src/components/choose-shose/image-search/imagefooter/analyzeitem/AnalyzeItem.tsx
src/components/choose-shose/image-search/imagefooter/analyzeitem/analyzeitem.css.ts
src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
src/components/choose-shose/image-search/imagefooter/imagefooter.css.ts

> ### Title
> * [Feat] 카메라 기능 구현 완
> ex) #31 
> ### PR Type
> * 카메라 아이콘 클릭시 캔버스에 화면 그림
> * 그린 화면 출력 해서 잘 작동하는지 확인
> ![image](https://github.com/user-attachments/assets/00031144-a71b-4dde-b295-ea1004f20550)
> * 추후 데이터 받아오면 비슷한 신발을 찾게하고 발견시 해당 신발 뜨도록 바꾸기

Feat:카메라 촬영 완--Jobemjun

---

src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
src/components/choose-shose/text-search/textheader/search-box/SearchBox.tsx
src/components/choose-shose/text-search/textheader/search-box/searchbox.css.ts
src/router/index.tsx

> ### Title
> * [Conf] Text/Image 라우터 설정 완료
> ex) #34 
> ### PR Type
> - [x] CONF :green_heart:: 빌드, 환경 설정
> * 라우터 설정 해서 App에서 따로 안띄오고 각자의 컴포넌트 이름을 쓰면 접속 가능 ex) /textSerach
> * ![image](https://github.com/user-attachments/assets/96095268-dd23-473c-baf9-8966307afb31)
> * navigate 를 공통을 사용할 수 있는 커스텀 훅 만들면 좋을듯

Conf:Text/Image-router 설정

---

src/components/common/modal/Modal.tsx
src/components/login/login.css.ts
src/components/signup/infoInput/SignUpInfoInputValid.tsx
src/components/signup/sizeinput/SignUpSizeInputValid.tsx
src/components/signup/sizeinput/usualsizeselect/UsualSizeSelect.tsx
src/router/index.tsx

> * style: SignUp Modal Modify
> #32 
> ### PR Type
> * 회원가입 페이지에 모달 적용
> * 에러 메시지 추가될 때 모션 위해 Modal.tsx에 일부 코드 추가 
(기존 모달 사용하신 페이지에 영향 없도록 추가했고 확인도 했는데 혹시나 꼬인 부분 있으면 말씀해주세요... 🥺)
> * 피그마 상 로그인, 회원가입 페이지는 일단 완료!...

style: SignUp Modal Modify

---

src/components/choose-shose/image-search/camera-window/cameracomponent/CameraComponent.tsx
src/components/choose-shose/image-search/camera-window/cameracomponent/cameracomponent.css.ts
src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
src/components/choose-shose/itemcard/ItemCard.tsx
src/components/choose-shose/itemcard/itemcard.css.ts
src/components/choose-shose/text-search/textheader/TextHeader.tsx

> ### Title
> * [Chore] 선택된 아이템카드 보더 처리
> #39 
> ### PR Type
> * 카메라 정중앙 위치
> * 이미지 검색-비슷한 상품 더보기 클릭시 나오는 아이템 카드 클릭시 보더 처리
> * ![image](https://github.com/user-attachments/assets/0e8052c6-a4d0-4735-852a-6bcae2b6d69f)
> * 갤러리 여는거 구현해야할듯

chore-SelectItmeCard-border---jobeomjun 선택된 카드 보더

---

src/components/choose-shose/itemcard/itemcard.css.ts
src/components/choose-shose/text-search/mainContainder/maincontainer.css.ts
src/components/choose-shose/text-search/textfooter/TextFooter.tsx
src/components/choose-shose/text-search/textheader/TextHeader.tsx
src/components/empty-shoes-room/EmptyShoesRoom.tsx
src/components/empty-shoes-room/choose/Choose.tsx
src/components/empty-shoes-room/header/Header.tsx
src/components/shoes-registry/ShoesRegistry.tsx
src/components/shoes-registry/shoesregistry.css.ts
src/components/slider/Slider.tsx
src/components/slider/slider.css.ts
src/stores/useShoesStore.ts

> ### Title
> * style: shoesinfo, shoesregistry, slider
> ex) #49
> ### PR Type
> * shoesinfo, shoesregistry ui 작업 완료 및 slider ui 수정 후 값 전달 완료
> *
> * 선택안했을 때 해야된다고 해야함, 서버에 입력한 정보 저장해야함, 사진 크기 변경

Style: shoesinfo final

---

src/components/login/Login.tsx
src/components/login/emaillogin/EmailLogin.tsx
src/components/login/emaillogin/emailLogin.css.ts
src/components/login/loginchatbot/loginbox/LoginButton.tsx
src/router/index.tsx

> style: Email Login
> #52 
> ### PR Type
> * 이메일 로그인 페이지가 없어서 제 맘대로 간단하게 했습니다...
> * 이메일 찾기랑 비밀번호 찾기도 없네요 생각해보니까.....................

style: Email Login

---

src/components/common/header/Header.tsx
src/components/common/header/header.css.ts
src/components/mypage/liked-and-viewed-history-button/LikedAndViewedHistoryButton.tsx
src/components/mypage/liked-and-viewed-history-button/likedAndViewedHistoryButton.css.ts
src/pages/mypage/Mypage.tsx

> ### Title
> * [Style] header position:fixed 적용 및 좋아요/최근 본 컴포넌트 스크롤이벤트 적용
> ex) #51
> ### PR Type
> * header position:fixed 적용 및 fixed만큼의 높이값 정렬, 좋아요/최근 본 컴포넌트 애니메이션 스크롤이벤트 처리
> <img src = "https://github.com/user-attachments/assets/856a5f9b-c902-4ef4-b2b6-34c3b8e8a009" width="50%" />
</div>
>

style: header position:fixed 적용 및 fixed만큼의 높이값 정렬, 좋아요/최근 본 컴포넌트 애니메이션 스크롤이벤트 처리

---

src/api/chatRequests.ts
src/components/chatbot/chatbot-bubble/chatBotBubble.css.ts
src/components/chatbot/product-filter/ProductFilter.tsx
src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
src/components/chatbot/product-recommendation/ProductRecommendation.tsx
src/components/common/product-recommendation-card/ProductRecommendationCard.tsx
src/components/common/product-recommendation-card/productRecommendationCard.css.ts
src/components/mypage/size-recommendation-card/SizeRecommendationCard.tsx
src/components/mypage/size-recommendation-card/sizeRecommendationCard.css.ts
src/pages/chatbot-page/chatBotPage.tsx
src/stores/useProductsStore.ts
src/types/chat.d.ts
src/types/keywords.d.ts
src/types/product.d.ts

> ### Title
> * [Feat] 채팅응답(키워드) 구현
> ex) #58 
> ### PR Type
> * 공통컴포넌트중 productrecommendationcard css 일부수정
> * chat.d.ts 타입 추가
> * keywords.d.ts 파일 생성
>* product.d.ts 파일 생성
> * useProductStore.ts 파일 생성
> * 키워드 선택 후 추천 상품 카드 더보기 클릭시 ProductRecommendation 모달 올라오면서 데이터 보여줌
> * 키워드 선택시 추천 상품카드 미리보기에 데이터 보여줌
> * ProductRecommendationCard.tsx 타입 떄문에 관련 컴포넌트들 다 에러떠있지만 굴러는갑니다.. 추후 …

Feat:completions keywords 

---

.yarnrc.yml
package.json

> ### Title
> * [Conf] yarn 버전 충돌로 인한 개발환경 통일
> ex) #63 
> ### PR Type
> - [x] CONF :green_heart:: 빌드, 환경 설정
> * yarn ver 3.6.3을 ver 1.22.22 으로 downgrade (충돌로 인한 개발환경 통일)
> <img width="864" alt="image" src="https://github.com/user-attachments/assets/e048b8fc-8d03-42ee-8565-a923e2977811">
> * 없음

conf: yarn version downgrade 3.6.3 => 1.22.22

---

package-lock.json
src/components/empty-shoes-room/EmptyShoesRoom.tsx
src/components/empty-shoes-room/emptyshoesroom.css.ts
src/components/empty-shoes-room/header/Header.tsx
src/components/empty-shoes-room/shoes-room/ShoesRoom.tsx
src/components/empty-shoes-room/shoes-room/shoesroom.css.ts
src/components/kebab/Kebab.tsx
src/components/kebab/kebab.css.ts
src/components/onboarding/OnBoarding.tsx
src/components/onboarding/OnBoarding2.tsx
src/components/onboarding/onboarding.css.ts
src/components/onboarding/onboarding2.css.ts
src/components/shoes-info/ShoesInfo.tsx
src/components/shoes-registry/ShoesRegistry.tsx
src/firebase/firebase.ts
src/router/index.tsx
src/stores/useRegistryStore.ts
src/stores/useShoesStore.ts
yarn.lock

> ### Title
> * [feat] firebase 연결
> ex) #67 
> ### PR Type
> * firebase 데이터 저장, 삭제, 불러오기, onboarding ui 변경, 신발 등록 유효성 검사, 신발장 셀렉트 박스 최신순, 등록순 구현
> * 
> * 수정 및 공유 아직 안됨, api에서 불러오는 신발 이미지 출력 해야함

feat: firebase

---

src/api/chatRequests.ts
src/components/chatbot/brand-plp/BrandPLP.tsx
src/components/chatbot/brand-plp/brandPLP.css.ts
src/components/chatbot/brand-recommendation-card/BrandRecommendationCard.tsx
src/components/chatbot/brand-recommendation/BrandRecommendation.tsx
src/components/chatbot/brand-recommendation/brandRecommendation.css.ts
src/components/chatbot/chatbot-bubble/ChatBotBubble.tsx
src/components/chatbot/product-filter-modal/productFilterModal.css.ts
src/components/chatbot/product-filter/ProductFilter.tsx
src/components/chatbot/product-filter/productFilter.css.ts
src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
src/components/common/chatbot-search-input/chatbotSearchInput.css.ts
src/components/common/modal/modal.css.ts
src/components/common/product-recommendation-card/ProductRecommendationCard.tsx
src/components/login/LoginHello.tsx
src/components/login/login.css.ts
src/components/login/loginchatbot/recommendbox/RecommendBox.tsx
src/components/mypage/size-recommendation-card/SizeRecommendationCard.tsx
src/components/mypage/size-recommendation-card/sizeRecommendationCard.css.ts
src/pages/chatbot-page/chatBotPage.tsx
src/stores/useBrandStore.ts
src/stores/useProductsStore.ts
src/types/brand.d.ts
src/types/chat.d.ts

> ### Title
> * [refactor] 브랜드PLP API 연결 및 파이어베이스 DB저장
> ex) #68 
> ### PR Type
> * 브랜드 PLP API 가 추가되었습니다
>* 파이어베이스 DB에 brands ,produts 데이터 저장
> * productFilterModal 높이값 수정
> * productFilter 스크롤 높이값 수정
> * 밑에 살짝나온 모달때문에 공유랑 싫어요 버튼 가려짐 이슈로 수정해야합니다
> * 하위 컴포넌트들 타입 오류때문에 빨간줄 떠있지만 신경쓰지 않으셔도 됩니다
> * 상품 PLP에 필터 모달 데이터에 따라서 높이값 다르게 설정해야겠습ㅁ니다

 refactor: 브랜드PLP API 연결 및 파이어베이스 DB저장

---

src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
src/stores/useProductStroe.ts
yarn.lock

> ### Title
> * fix-변수명 교체
> #65
> ### PR Type
> * 커밋당시 잘못 반영된 변수명 교체
> * 변수명 교체라 스크린샷 없음
> * 없습니다

fix-변수명오류 교체

---

src/App.tsx
src/components/empty-shoes-room/EmptyShoesRoom.tsx
src/components/empty-shoes-room/user-profile/UserProfile.tsx
src/components/shoes-registry/ShoesRegistry.tsx
src/components/sidemenu/SidemenuMypageLinks.tsx
src/pages/mypage/Mypage.tsx

> ### Title
> * [Feat]  sidemenu 및 mypage 구현
> ex) #106
> ### PR Type
> * 구체적인 작업 내용을 작성해주세요.
> * 작업이 완료된 화면을 업로드해주세요.
> * 추후 논의할 점에 대해 작성해주세요.

feat: 신발장 user id data test

---

src/components/login/Login.tsx
src/components/login/LoginHello.tsx
src/components/login/emaillogin/EmailLogin.tsx
src/components/login/find/FindEmail.tsx
src/components/login/find/FindPassword.tsx
src/components/login/login.css.ts
src/components/signup/infoInput/GoogleSignUpPlus.tsx
src/components/signup/infoInput/SignUpInfoInputValid.tsx
src/components/signup/sizeinput/SignUpSizeInputValid.tsx
src/components/toastmessage/toast-message.css.ts

> style: alert to toastmessage
> #102 
> ### PR Type
> * 모든 alert를 토스트 메시지로 수정
> * 새로 만들었던 페이지에 반응형 깜박했던 거 적용
성민님 토스트 메시지 적용
> * 할 일~...
- 로그인한 사용자 이름 반영
- 유효성 검사 방식 수정

style: alert to toastmessage

---

src/components/empty-shoes-room/EmptyShoesRoom.tsx
src/components/empty-shoes-room/emptyshoesroom.css.ts
src/components/empty-shoes-room/user-profile/UserProfile.tsx
src/pages/mypage/Mypage.tsx

> ### Title
> * user data
> ex) #104
> ### PR Type
> * userdata 받아와서 신발장 출력 및 토스트메시지 버그 픽스(렌더링)
> * 
> *토스트 메시지 새로고침시에는 아직 안됨

Feat user data

---

src/components/chatbot/brand-recommendation/BrandRecommendation.tsx
src/components/common/chatbot-search-input/ChatbotSearchInput.tsx
src/components/common/product-recommendation-card/ProductRecommendationCard.tsx
src/components/login/LoginHello.tsx
src/pages/share-page/SharePage.tsx
src/stores/useProductsStore.ts

> ### Title
> *[refactor]타입 수정 및 chatHistory 날짜 추가
> ex) #113 
> ### PR Type
> * sharePage 타입 수정
> * 채팅 post 할 경우 파이어베이스에 날짜 및 시간 저장
> * 채팅 보낼경우 마지막 단어 한번 더 보내지는 버그 수정
> * 바뀐 화면 없음
> * 타입 수정 해야할곳이 chatbotpage만 하면됨
> * 로그인 하지 않은 상태일경우 채팅 못보내게 해야함

refactor: 타입 수정 및 chatHistory 날짜 추가

---

src/components/choose-shose/gallery/Gallery.tsx
src/components/choose-shose/image-search/analyzeitem/succesproduct/SuccesProduct.tsx
src/components/choose-shose/image-search/analyzeitem/succesproduct/succesproduct.css.ts
src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
src/components/choose-shose/image-search/imageupload/ImageUpload.ts
src/components/choose-shose/itemcard/ItemCard.tsx
src/components/choose-shose/itemcard/itemcard.css.ts
src/components/choose-shose/text-search/textupload/TextUpload.ts
src/firebase/firebase.ts
src/stores/useGalleryStore.ts
src/stores/useImageSearchStore.ts
src/stores/useProductsStore.ts

> ### Title
> * [Feat] 이미지 검색 파이어 베이스 작업
> #103 
> ### PR Type
> * 촬영한 이미지나 갤러리에서 선택한 이미지를 base64로 변환하여 파이어베이스 올림
> * 올린 이미지의 URL을 받아와 이미지 검색 API에 전달
> * 이후 파이어베이스에 저장된 이미지 삭제하여 저장공간 확보
> * ![image](https://github.com/user-attachments/assets/cd289db9-e584-4eb3-a583-8049f92252c6).
> * 해당 사용자의 UID 혹은 userName을 가져와 이미지가 겹치지 않도록 처리
> * 로그인시 user 데이터 전역상태에 저장하면 텍스트검색 기록 파이어베이스에 저장 …

feat-firebaseImageSearch--jobeomjun

---

src/components/common/header/Header.tsx
src/components/empty-shoes-room/user-profile/UserProfile.tsx
src/components/sidemenu/SideMenu.tsx
src/components/sidemenu/SidemenuMypageLinks.tsx
src/pages/mypage/Mypage.tsx
src/pages/mypage/mypage.css.ts
src/styles/responsive.css.ts

> ### Title
> * [Feat] 마이페이지
> ex) #106
> ### PR Type
> * navigate 함수 사용방식 통일
> * 프로필이미지 업로드 시 사이즈규격 및 둥근이미지 유지되게 수정
> * 
> * 
> * 
@[laurenCho9](https://github.com/Prefitt-11-supreme/11-supreme/commits?author=laurenCho9)
laurenCho9 committed now
[Revert "refactor: navigate 함수 사용방식 통일"](https://github.com/Prefitt-11-supreme/11-supreme/commit/8da1bb4ca31e097e5c66f628d3a27bf02d177ffb) …

Feat mypage

---

src/components/choose-shose/image-search/analyzeitem/succesproduct/SuccesProduct.tsx
src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
src/components/choose-shose/itemcard/ItemCard.tsx
src/components/choose-shose/itemcard/itemcard.css.ts
src/components/choose-shose/text-search/TextSearch.tsx
src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
src/components/choose-shose/text-search/search-box/SearchBox.tsx
src/components/choose-shose/text-search/textfooter/TextFooter.tsx
src/components/shoes-registry/ShoesRegistry.tsx
src/stores/useImageSearchStore.ts
src/stores/useSelectItemStore.ts

> ### Title
> * [Fix, Refactor] 텍스트 검색과 이미지 검색에서 데이터 넘기는 오류 처리
> #120 
> ### PR Type
> * 텍스트 검색에서 선택 완료 안누르고 나가도 아이템 선택되던 버그 수정
> * 아이템 제일 처음거 선택하면 신발등록에서 border 나오던거 수정
> * 아이템 클릭해야 선택완료 나오는거로 처리
> * 이미지 검색시 선택완료 눌러도 신발정보 안넘기던 버그 수정
> * 화면상 보여지지 않음
> * 파이어베이스 빨리해야지

refactor-imagesearch---jobeomjun

---

src/components/chatbot/brand-plp/BrandPLP.tsx
src/components/chatbot/product-filter-detail/ProductFilterDetail.tsx
src/components/chatbot/product-filter/ProductFilter.tsx

> ### Title
> * [Feat] 브랜드 PLP 상품 필터링
> ex) #124 
> ### PR Type
> * 브랜드 PLP 상품 필터링
https://github.com/user-attachments/assets/f30d1f11-0552-46e3-8b5e-4c2f58bb3523
> * 바텀시트 필터링은 가격도 같이 해야하는것같아서 따로하지 않았습니다.

Feat: 브랜드 PLP 상품 필터링

---

src/components/chatbot/brand-recommendation/BrandRecommendation.tsx
src/components/chatbot/product-filter/ProductFilter.tsx
src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
src/components/common/chatbot-search-input/ChatbotSearchInput.tsx
src/components/common/share-modal/ShareModal.tsx
src/components/login/LoginHello.tsx
src/hooks/useChatCompletionHook.ts
src/pages/share-page/SharePage.tsx
src/stores/useChatStore.ts
src/stores/useUserStore.ts
src/types/chatItem.d.ts
src/utils/sharedChatHistoryUtils.ts

> ### Title
> [fix]회원별 채팅방 구분 및 채팅공유 데이터 구분작업
> ex) #131 
> ### PR Type
> * 회원별 채팅 구별
> * 소셜로그인, 일반 로그인 이름 구별
> * 공유용 디비 생성 
> * 채팅 보내는 함수 분리 작업
> * 화면 변화 없음
> * 새 채팅방 만든다 -> 채팅방을 한 컴포넌트에서 다 처리를 해야할것같은데 모루겠읍니다

refactor: 회원별 채팅방 구분 및 채팅공유 데이터 구분작업

---

src/components/common/share-modal/ShareModal.tsx
src/components/login/LoginHello.tsx
src/hooks/useChatCompletionHook.ts
src/pages/share-page/SharePage.tsx

> ### Title
> *[Refactor] 채팅 컴포넌트 통일
> ex) #134 
> ### PR Type
> * /chatbot 페이지에서 따로놀던 관심키워드를 LoginHello에 합쳤습니다
> * 공유 모달에 날짜를 채팅 생성 날짜로 변경
> * 
https://github.com/user-attachments/assets/a4df2c52-7c75-422d-b62d-9a83e48a7a14
> * 채팅 두번씩 날라가는데 데이터는 한번만 저장됨 이거 어디서 이러는지 찾아야하고
> * 새 채팅방 만들어야함

Refactor:채팅 컴포넌트 통일

---

src/components/choose-shose/firebase/textupload/TextUpload.ts
src/components/choose-shose/text-search/search-box/SearchBox.tsx
src/components/onboarding/OnBoarding.tsx
src/stores/useSelectItemStore.ts
src/stores/useTextSearchStore.ts
src/stores/useUserStore.ts
src/types/user.d.ts

> ### Title
> * [Feat] 파이어베이스 텍스트검색 작업
> #137 
> ### PR Type
> * 신발 등록이나 이미지 검색으로 넘어갈 때 파이어베이스 doc에 uid를 기반으로 텍스트 검색 기록 저장
> * 온보딩에서 유저 데이터를 가져올 때 검색 기록도 같이 가져오기
> * ![image](https://github.com/user-attachments/assets/e20678db-89d1-4fd5-af1c-dfade36ca521)
> * 없습니다

Feat-FirebaseTextsearch-jobeomjun

---

src/components/common/chatbot-search-input/ChatbotSearchInput.tsx
src/components/common/modal/modal.css.ts
src/components/login/Login.tsx
src/components/login/LoginHello.tsx
src/components/login/emaillogin/EmailLogin.tsx
src/components/login/find/FindEmail.tsx
src/components/login/find/FindPassword.tsx
src/components/onboarding/OnBoarding.tsx
src/components/signup/infoInput/GoogleSignUpModal.tsx
src/components/signup/infoInput/SignUpInfoModal.tsx
src/components/signup/sizeinput/SignUpSizeModal.tsx
src/components/toastmessage/toast-message.css.ts
src/pages/chatbot-page/chatBotPage.tsx
src/stores/useChatStore.ts
src/stores/useModalStore.ts

> ### 🌎Pull Request
> refactor: login/signup
> #132 
> ### PR Type
> * 회원가입 후 > /hello(로그인 후 첫 화면)로 이동 
> * 챗봇 로그인한 사용자 이름 반영
> * 회원가입 컴포넌트들 따로 페이지가 아닌 모달로 올라오게 수정
> * 로그인한 사용자만 채팅 입력 가능하게 ChatbotSearchInput에서 handleInputChange 수정 (로그인 상태가 아닐 때 입력 시도하면 로그인 유도 토스트 메시지 표시)
> * 온보딩 페이지에서 로그인 되어 있을 때 콘솔에 유저 정보 두 번 찍히는 중복 호출 방지
> * 회원가입 시 이미 가입된 이메일 오류와 안전하지 않은 비밀번호 오류 중첩될 경우 이미 가입된 이메일 오류 우선되게 수정 
> * 인증은 되었으나 …

refactor: login/signup

---

src/components/chatbot/brand-recommendation/BrandRecommendation.tsx
src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
src/components/login/LoginHello.tsx
src/components/sidemenu/SideMenu.tsx
src/components/sidemenu/SidemenuList.tsx
src/hooks/useChatHistoryHook.ts
src/router/index.tsx

> ### Title
> * [refactor] 새로운 채팅방 경로 수정 및 공유 페이지 아이디 수정
> ex) #146 
> ### PR Type
> * 경로 수정이 있습니다
> * 새 채팅방이 생기면서 안되던 공유기능 버그 고쳤습니다
> * 최초로그인시 가입환영인사, 맞춤상품 추천 둘다뜨는 오류 수정
> * 새 채팅방 생성시 가입환영인사 뜨는 오류 수정
> * 만들어진 채팅방 목록 사이드메뉴에 출력
> 
https://github.com/user-attachments/assets/eb5fcb1d-6037-4cad-9869-4e69d2841cb4
> * 아직도 채팅 두번보이는거 안고침 이슈
> * 영상에 있듯. 새채팅방 만들면 인풋창이 새로고침해야 보여서 또 …

refactor: 새로운 채팅방 경로 수정 및 공유 페이지 아이디 수정

---

src/App.tsx
src/components/choose-shose/image-search/ImageSearch.tsx
src/components/choose-shose/text-search/TextSearch.tsx
src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
src/components/choose-shose/text-search/mainContainder/maincontainer.css.ts
src/components/empty-shoes-room/EmptyShoesRoom.tsx
src/components/foot-info/FootInfo.tsx
src/components/login/LoginHello.tsx
src/components/onboarding/OnBoarding.tsx
src/components/shoes-info/ShoesInfo.tsx
src/components/shoes-registry/ShoesRegistry.tsx
src/pages/bridge-page/bridgePage.tsx
src/pages/chatbot-page/chatBotPage.tsx
src/pages/liked-page/LikedPage.tsx
src/pages/not-found/notFound.tsx
src/pages/share-page/SharePage.tsx
src/pages/viewed-history-page/ViewedHistoryPage.tsx
src/router/index.tsx

> ### Title
> * [Refactor] 아울렛 설정
> #149
> ### PR Type
> * 각 페이지에 적용되있던 responsiv를 아울렛으로 변경
> * 라우터 설정시 NotFound 컴포넌트는 밖에다가 설정하여 전체화면 차지하도록 설정
> * 코드의 간소화이기에 화면은 똑같습니다.
> * 없습니다

Refactor-Responsiv---jobeomjun-아울렛 설정

---

src/components/common/modal/modal.css.ts
src/components/mypage/liked-in-brand/LikedInBrand.tsx
src/components/mypage/liked-in-brand/likedInBrand.css.ts
src/components/mypage/size-recommendation-card/SizeRecommendationCard.tsx
src/components/sidemenu/SideMenu.tsx
src/hooks/useAddUserIdToFirestoreHook.ts
src/hooks/useChatHistoryHook.ts
src/pages/liked-page/LikedPage.tsx
src/pages/liked-page/likedPage.css.ts
src/pages/viewed-history-page/ViewedHistoryPage.tsx
src/pages/viewed-history-page/viewedHistoryPage.css.ts
src/stores/useLikedStore.ts
src/stores/useViewedHistoryStore.ts
src/types/product.d.ts

> ### Title
> * 제목은 '[Feat] 홈 페이지 구현'과 같이 작성합니다.
> ex) #129 
> ### PR Type
> * 좋아요-브랜드, 상품 과 최근본의 데이터 구조 변경
> * 브랜드 로고 불러오는 구조 변경 
> * 좋아요-상품 테스트 중... 
> * <img width="292" alt="image" src="https://github.com/user-attachments/assets/ed13e955-16c1-424c-9a09-dfebf4c2475e">
> * 내부 브랜치 충돌 너무 많아서 현재 작업까지 검증 마치고 PR

Fix liked and viewedhistory filtered chohayoon

---

src/App.tsx
src/components/common/header/header.css.ts
src/components/login/Login.tsx
src/components/login/find/FindEmail.tsx
src/components/login/find/FindPassword.tsx
src/components/login/login-hello/LoginHello.tsx
src/components/login/login-hello/loginHello.css.ts
src/components/login/login.css.ts
src/components/onboarding/OnBoarding.tsx
src/components/onboarding/onboarding.css.ts
src/components/sidemenu/sidemenu.css.ts
src/components/signup/signup.css.ts
src/components/signup/sizeinput/SignUpSizeModal.tsx
src/components/signup/sizeinput/infobox/infoBox.css.ts
src/components/signup/sizeinput/sizetypebutton/buttonblank/buttonBlank.css.ts
src/components/signup/sizeinput/sizetypebutton/buttonfill/buttonFill.css.ts
src/components/signup/sizeinput/usualsizeselect/usualsizeSelect.css.ts
src/router/index.tsx
src/styles/responsive.css.ts

> ### Title
> * [style] helloLogin까지 수정완료
> ex) #160 
> ### PR Type
> * 공통레이아웃 -> 포지션 작업 되어있는거 flex로 수정
> * 온보딩
> * 로그인
> * 아이디,비번찾기
> * 회원가입
> * 로그인 페이지
> * 사이드메뉴 높이
> * LoginHello 페이지 
> * LoginHello css 분리
> * header 너비
수정.
> * x
> * 갈길이 멀어요

style: helloLogin까지 수정완료

---

src/components/empty-shoes-room/EmptyShoesRoom.tsx
src/components/empty-shoes-room/choose/Choose.tsx
src/components/empty-shoes-room/choose/choose.css.ts
src/components/empty-shoes-room/header/Header.tsx
src/components/shoes-registry/ShoesRegistry.tsx
src/components/shoes-registry/shoesregistry.css.ts
src/components/shoes-registry/star-rating/StarRating.tsx
src/components/slider/Slider.tsx
src/stores/useRegistryStore.ts

> ### Title
> * fix loading
> ex) #144 
> ### PR Type
> * shoesroom 데이터 없을 때 로딩페이지, 유효성 검사 로직 수정, registry css 변경, 렌더링 최적화 완료
> * 작업이 완료된 화면을 업로드해주세요.
> * 슬라이더는 최적화 못함

fix-loading

---

src/App.tsx
src/components/common/button/Button.tsx
src/components/common/button/button.css.ts
src/components/empty-shoes-room/emptyshoesroom.css.ts
src/components/empty-shoes-room/user-profile/UserProfile.tsx
src/components/empty-shoes-room/user-profile/userprofile.css.ts
src/components/shoes-info/shoes-info.css.ts
src/components/shoes-registry/ShoesRegistry.tsx
src/components/shoes-registry/shoesregistry.css.ts
src/components/sidemenu/SidemenuMypageLinks.tsx
src/components/sidemenu/sidemenuMypageLinks.css.ts
src/index.css.ts
src/pages/mypage/Mypage.tsx
src/styles/responsive.css.ts
src/types/button.d.ts

> ### Title
> *  feat: userimage
> ex) #166 
> ### PR Type
> * user 이미지 스토리지에 저장 및 파이어스토어 user에 profileimage 추가, mypage, userprofile, sidemenu 이미지 띄움
css 살짝 수정
> * ![image](https://github.com/user-attachments/assets/f76fe2fc-dfb6-4903-8309-5e46a6ba4f78)
> * x

feat: userImage

---

src/components/choose-shose/image-search/analyzeimage/analyzeimage.css.ts
src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
src/components/choose-shose/text-search/search-box/searchbox.css.ts
src/components/choose-shose/text-search/textfooter/textfooter.css.ts
src/components/common/button/button.css.ts
src/components/common/header/header.css.ts
src/components/deleteuser/DeleteUserModal.tsx
src/components/login/login-hello/loginHello.css.ts
src/components/login/login.css.ts
src/components/shoes-registry/ShoesRegistry.tsx
src/components/shoes-registry/shoesregistry.css.ts
src/components/signup/signup.css.ts
src/components/toastmessage/toast-message.css.ts
src/styles/media.css.ts
src/styles/responsive.css.ts

> ### Title
> * [Fix] 공통 CSS 스타일 버그 수정
> #167
> ### PR Type
> * 공통 컴포넌트 픽스드 크기 오류나던거 수정
> ![image](https://github.com/user-attachments/assets/dccf6557-2a5a-4637-a2b1-939891cbd003)
> * 없습니다

Fix commonstylefix jobeomjun

---

src/components/common/header/Header.tsx
src/components/common/header/header.css.ts
src/components/deleteuser/DeleteUserModal.tsx
src/components/deleteuser/deleteUserModal.css.ts
src/components/login/Login.tsx
src/components/login/emaillogin/EmailLogin.tsx
src/components/login/find/FindEmail.tsx
src/components/login/find/FindPassword.tsx
src/components/login/login.css.ts
src/components/onboarding/OnBoarding.tsx
src/components/onboarding/onboarding.css.ts
src/components/signup/infoInput/GoogleSignUpModal.tsx
src/components/signup/infoInput/SignUpInfoModal.tsx
src/components/signup/sizeinput/SignUpSizeModal.tsx
src/components/toastmessage/toast-message.css.ts

> ### 🌎Pull Request
> fix: login signup css
> #155 
> ### PR Type
> [뻑난 거 고치기]
> * 회원탈퇴, 회원가입 모달 올라올 때 가로 길이 맞추기
> * 회원탈퇴 배경 세로 길이 맞추기
> * 토스트 메시지 중앙 정렬 맞추기
> * 헤더 가로 길이 맞추기... 
> (리베이스 받아도 그대로라서...... 근데 너무 거슬려서 좀 수정 했어요............... 원래 코드에서 몇 줄 주석 처리만 함... 공통 헤더 파일 확인 요망...)
>
> [짜잘한 수정]
> * 회원탈퇴 탈퇴하기, 취소 버튼 사이 간격 좀 줄임 (미관상)
> * 회원탈퇴 후 로그인 말고 온보딩으로 이동 
> * 모달 전환될 때 딜레이 추가 (모션 끊겨 보여서)
> * 이메일 로그인에서 이메일 입력할 …

fix: login signup css

---

src/components/login/login-hello/LoginHello.tsx
src/components/login/login-hello/loginHello.css.ts

> ### Title
> *[style] loginHelloInputContainer 삭제
> ex) #171 
> ### PR Type
> * 질문 카드 안나와서 loginHelloInputContainer 스타일 지웠습니다
> * 바뀐거 없음
> * 모바일 환경은 어떡한담 ㅎ.ㅎ..

style: loginHelloInputContainer 삭제

---

.github/workflows/node.js.yml

> ### Title
> * [deploy] aws s3 배포
> ex) 없음
> ### PR Type
> * aws s3 배포
> * x
> * x

deploy: Create node.js.yml

---

.github/workflows/node.js.yml

> ### Title
> * [deploy] 빌드 버전 수정
> ex) x
> ### PR Type
> * x
> * x
> * x

deploy: Update node.js.yml

---

.gitignore

> ### Title
> * deploy: envproduction 추가, 이그노어 추가
> ex) #184 
> ### PR Type
> * .env.production 파일추가
> * x
> * x

deploy: envproduction 추가, 이그노어 추가

---

src/api/axiosClient.ts
src/components/chatbot/brand-recommendation-card/BrandRecommendationCard.tsx
src/components/chatbot/brand-recommendation-card/brandRecommendationCard.css.ts
src/components/chatbot/brand-recommendation/BrandRecommendation.tsx
src/components/chatbot/chatbot-bubble/ChatBotBubble.tsx
src/components/chatbot/product-filter/ProductFilter.tsx
src/components/common/chatbot-search-input/ChatbotSearchInput.tsx
src/components/common/header/Header.tsx
src/components/common/modal/Modal.tsx
src/components/login/login-hello/LoginHello.tsx
src/components/mypage/size-recommendation-card/SizeRecommendationCard.tsx
src/components/mypage/size-recommendation-card/sizeRecommendationCard.css.ts
src/hooks/useFetchChatHistoryHook.ts
vite.config.ts

> ### Title
> * [style] 상품PLP, 브랜드 PLP 너비 수정, img 태그 너비,높이 지정
> ex) #188 
> ### PR Type
> * 이미지 태그 width,height 지정, 누락된 alt 추가
> * vite.config.js 
server: {
hmr: false
}
코드 추가
> * userFetchChatHistoryHook.ts -> bfcache 관련 이벤트 처리
> * 변화없음
> * 웹소켓을 안쓰는데 bfcache 진단이 뜸.. Vite의 개발 서버가 WebSocket을 사용하여 핫 모듈 리로딩(HMR)을 구현하기 때문에 이런 문제가 발생하는것같음... 배포 서버에서 확인해봐야할듯

style: 상품PLP, 브랜드 PLP 너비 수정, img 태그 너비,높이 지정

---

src/components/chatbot/brand-recommendation-card/BrandRecommendationCard.tsx
src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
src/components/common/product-recommendation-card/ProductRecommendationCard.tsx
src/components/login/login-hello/LoginHello.tsx
vite.config.ts

> ### Title
> * [chore] 프록시 설정, 이미지 width,height 추가
> ex) #191 
> ### PR Type
> * s3 배포시 데이터 요청을 프론트 배포 주소로 요청하여 프록시 설정
> * img 태그에 width, height 추가
> *바뀐 화면 없음
> * 성능은 배포된 서버에서 확인하기..~

chore: 프록시 설정, 이미지 width,height 추가

---

vite.config.ts

> ### Title
> * [chore] 프록시 주소 수정
> ex) #193 
> ### PR Type
> * 프록시 주소 수정
> *x
> * x

chore: 프록시 주소 수정

---

src/api/axiosClient.ts

> ### Title
> * [deploy]요청 인터셉터 코드 추가
> ex) #197 
> ### PR Type
> * api/axiosClient.ts -> 요청 인터셉터 코드 추가
> * x
> * 그만 머지하고싶다...

deploy: 요청 인터셉터 코드 추가

---

.github/workflows/node.js.yml

> ### Title
> * [deploy] 워크플로우 env 수정
> ex) #203 
> ### PR Type
> * 워크플로우 env 수정
> * 바뀐화면없음
> * x

deploy: 워크플로우 env 수정

---

.github/workflows/node.js.yml

> ### Title
> * [chore] 워크플로우 수정
> ex) x
> ### PR Type
> * 문법 구조 수정
> * x
> * x

chore:워크플로우 수정

---

src/components/chatbot/brand-plp/BrandPLP.tsx
src/components/chatbot/brand-plp/brandPLP.css.ts
src/components/chatbot/product-filter/ProductFilter.tsx
src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
src/components/common/product-recommendation-card/ProductRecommendationCard.tsx
src/components/deleteuser/DeleteUserModal.tsx
src/components/login/login-hello/LoginHello.tsx
src/components/mypage/liked-in-brand/LikedInBrand.tsx
src/components/mypage/size-recommendation-card/SizeRecommendationCard.tsx
src/components/mypage/size-recommendation-card/sizeRecommendationCard.css.ts
src/components/sidemenu/sidemenu-mypage-link/SidemenuMypageLink.tsx
src/firebase/onUserFirstLogin.ts
src/pages/mypage/Mypage.tsx
src/pages/mypage/liked-page/LikedPage.tsx
src/pages/mypage/liked-page/likedPage.css.ts
src/pages/mypage/viewed-history-page/ViewedHistoryPage.tsx
src/pages/mypage/viewed-history-page/viewedHistoryPage.css.ts
src/pages/share-page/SharePage.tsx
src/stores/useMyLikedBrandStore.ts
src/stores/useMyLikedProductStore.ts
src/stores/useMyViewedProductStore.ts
src/stores/useUidAddStore.ts
src/types/product.d.ts

> ### Title
> * [Fix] 좋아요(상품카드, 브랜드), 최근본(상품카드) 기능 구현 및 zustand로 전역상태관리
> ex) #207 
> ### PR Type
> * 브랜드 좋아요 기능 구현 완료
> * 상품카드 좋아요 기능 구현 완료
> * 상품카드 최근본 기능 구현 완료
> * ![좋아요 최근본 구현(1)_채팅창](https://github.com/user-attachments/assets/2475fd91-b4ce-4db8-9198-d8a1c44b32d6)
> * ![좋아요 최근본 구현(2)_더보기 모달창(브랜드 좋아요 …

Fix liked viewed history page chohayoon
